#!/bin/bash
echo "Updating Whaticket, please wait."

git pull
cd backend
npm install --force
rm -rf dist
npm run build
npx sequelize db:migrate
npx sequelize db:seed
cd ../frontend
npm install --force
rm -rf build
npm run build
pm2 restart all

echo "Update finished. Enjoy!"
